import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {JSDOM} from 'jsdom';
const html=readFileSync(new URL('../src/page.html',import.meta.url),'utf8');
const cp={id:'cp:1',source:'compras',title:'Xiaomi H50 Pro',priceUsd:455,store:'2 ofertas',availability:'unknown',images:['https://img.test/1.png'],productPath:'/phone_123/',productUrl:'https://www.comprasparaguai.com.br/phone_123/'};
const lg={id:'lg:1',source:'lg',title:'Phone LG',priceUsd:100,store:'LG Importados',availability:'in_stock',images:['https://img.test/lg1.png','https://img.test/lg2.png'],galleryLoaded:true,productUrl:'https://www.lgimportados.com/produto/1'};
const stores={lg,compras:cp};
for(const [source,label,usd] of [['visaovip','VisãoVip',180],['shoppingchina','Shopping China',190],['cellshop','Cellshop',200],['casamaringa','Casa Maringá',210]])stores[source]={...lg,id:source+':1',source,title:'Phone '+label,store:label,priceUsd:usd,via:source==='casamaringa'?undefined:'compras',availability:source==='casamaringa'?'out_of_stock':'unknown',productUrl:'https://store.test/'+source,referenceUrl:source==='casamaringa'?undefined:'https://www.comprasparaguai.com.br/phone__456/'};
const exchange={base:'USD',rates:{BRL:5.2,PYG:6000,ARS:1600},updatedLabel:'Atualizado em: 13 de Setembro de 2026 às 09:45'};
const response=data=>({ok:true,json:async()=>structuredClone(data)});
const pageResponse=(source,page=1,totalPages=1,list)=>response({items:list||[{...stores[source],id:page===1?stores[source].id:source+':'+page,searchRank:page-1}],sources:{[source]:'ok'},pagination:{[source]:{page,totalPages,nextPage:page<totalPages?page+1:null}}});
const wait=async check=>{for(let i=0;i<600;i++){if(check())return;await new Promise(r=>setTimeout(r,5));}throw Error('UI did not reach expected state');};
const settled=d=>d.querySelector('#search-progress').textContent.includes('foram consultadas')||d.querySelector('#retry-missing');
async function setup(options={}) {
 const calls=[];
 const dom=new JSDOM(html,{url:'https://local.test/',runScripts:'dangerously',beforeParse(w){
  w.IntersectionObserver=class{observe(){} unobserve(){} disconnect(){}};
  w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};
  w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');this.dispatchEvent(new w.Event('close'));};
  w.fetch=async (url,config)=>{
   const u=new URL(url,'https://local.test');calls.push(u);
   if(u.pathname==='/api/exchange')return options.rateFails?{ok:false}:response(exchange);
   if(u.pathname==='/api/search')return options.search?options.search(u,config):pageResponse(u.searchParams.get('source'),+u.searchParams.get('page'));
   return options.detailFails?{ok:false}:response({images:['https://img.test/1.png','https://img.test/2.png'],offers:[{store:'Loja A',title:'H50 Pro',priceUsd:455,url:'https://store.test/a'},{store:'Loja B',title:'H50 Pro',priceUsd:460,url:'https://store.test/b'}]});
  };
 }});
 const d=dom.window.document;
 const submit=query=>{d.querySelector('#query').value=query;d.querySelector('#search').dispatchEvent(new dom.window.Event('submit',{cancelable:true}));};
 submit('Xiaomi');if(!options.defer)await wait(()=>settled(d));
 return {dom,d,calls,submit};
}
const card=(d,id)=>Array.from(d.querySelectorAll('.card')).find(c=>c.dataset.key===id);

test('LG card arrows change picture without opening details',async()=>{const {dom,d}=await setup();try{const c=card(d,'lg:1');assert.equal(c.querySelector('.product-image').src,lg.images[0]);c.querySelector('.next').click();assert.equal(c.querySelector('.product-image').src,lg.images[1]);assert.equal(d.querySelector('dialog').open,false);}finally{dom.window.close();}});
test('opening CP card lists every store and hydrates card gallery',async()=>{const {dom,d}=await setup();try{card(d,'cp:1').querySelector('.title-button').click();await wait(()=>d.querySelectorAll('.offer').length===2);assert.match(d.querySelector('#offer-list').textContent,/Loja A/);assert.match(d.querySelector('#offer-list').textContent,/460,00/);assert.equal(card(d,'cp:1').querySelector('.photo-count').textContent,'1 / 2');d.querySelector('#close-detail').click();assert.equal(d.querySelector('dialog').open,false);}finally{dom.window.close();}});
test('sort and every source filter work immediately without new requests',async()=>{const {dom,d,calls}=await setup();try{const original=calls.length;d.querySelector('#sort').value='price-asc';d.querySelector('#sort').dispatchEvent(new dom.window.Event('change'));assert.equal(d.querySelector('.title-button').textContent,'Phone LG');for(const source of Object.keys(stores)){d.querySelector('#source').value=source;d.querySelector('#source').dispatchEvent(new dom.window.Event('change'));assert.equal(d.querySelectorAll('.card').length,1);assert.equal(d.querySelector('.card').dataset.key,stores[source].id);}assert.equal(calls.length,original);}finally{dom.window.close();}});
test('offer failure keeps origin link and retry action',async()=>{const {dom,d}=await setup({detailFails:true});try{card(d,'cp:1').querySelector('.title-button').click();await wait(()=>d.querySelector('.dialog-error'));assert.ok(d.querySelector('.origin-link'));assert.match(d.querySelector('.dialog-error').textContent,/Tentar novamente/);}finally{dom.window.close();}});
test('image failure replaces broken image while retaining next arrow',async()=>{const {dom,d}=await setup();try{const c=card(d,'lg:1');c.querySelector('img').dispatchEvent(new dom.window.Event('error'));assert.ok(c.querySelector('.no-photo'));assert.ok(c.querySelector('.next'));}finally{dom.window.close();}});
test('all four retailers open with their own price, source and product link',async()=>{const {dom,d}=await setup();try{for(const source of ['visaovip','shoppingchina','cellshop','casamaringa']){card(d,source+':1').querySelector('.title-button').click();assert.match(d.querySelector('#offer-list').textContent,new RegExp(stores[source].store));assert.ok(d.querySelector('.direct-offer-action').href.endsWith(source));if(source!=='casamaringa')assert.match(d.querySelector('#offer-list').textContent,/via Compras Paraguai/);d.querySelector('#close-detail').click();}}finally{dom.window.close();}});
test('homepage exchange shows all currencies and source timestamp',async()=>{const {dom,d}=await setup();try{assert.match(d.querySelector('#exchange-values').textContent,/R\$ 5,20/);assert.match(d.querySelector('#exchange-values').textContent,/G\$ 6\.000,00/);assert.match(d.querySelector('#exchange-values').textContent,/AR\$ 1\.600,00/);assert.match(d.querySelector('#exchange-date').textContent,/09:45/);}finally{dom.window.close();}});
test('exchange failure does not show a made-up rate or prevent searching',async()=>{const {dom,d}=await setup({rateFails:true});try{assert.match(d.querySelector('#exchange-values').textContent,/indisponível/);assert.equal(d.querySelectorAll('.card').length,6);assert.doesNotMatch(d.querySelector('#exchange-values').textContent,/5,20/);}finally{dom.window.close();}});
test('known stale exchange is explicitly marked if refresh fails',async()=>{const options={};const {dom,d}=await setup(options);try{options.rateFails=true;d.querySelector('#refresh-exchange').click();await wait(()=>d.querySelector('#exchange-date').textContent.includes('Não foi possível atualizar'));assert.match(d.querySelector('#exchange-values').textContent,/5,20/);assert.ok(d.querySelector('.exchange.is-stale'));}finally{dom.window.close();}});
test('client loads every page including page 31 and deduplicates repeated IDs',async()=>{const {dom,d,calls}=await setup({search:u=>{const source=u.searchParams.get('source'),page=+u.searchParams.get('page');return pageResponse(source,page,source==='cellshop'?31:1,source==='cellshop'?[{...stores.cellshop,id:'cellshop:'+page},stores.cellshop]:undefined);}});try{assert.ok(calls.some(u=>u.searchParams.get('source')==='cellshop'&&u.searchParams.get('page')==='31'));assert.match(d.querySelector('#result-title').textContent,/36 resultados/);assert.match(d.querySelector('#search-progress').textContent,/36 páginas/);while(!d.querySelector('#more').hidden)d.querySelector('#more').click();assert.equal(d.querySelectorAll('.card').length,36);}finally{dom.window.close();}});
test('failed later page preserves data and retries only pending pages',async()=>{let fail=true;const {dom,d,calls}=await setup({search:u=>{const source=u.searchParams.get('source'),page=+u.searchParams.get('page');if(source==='cellshop'&&page===2&&fail)return {ok:false};return pageResponse(source,page,source==='cellshop'?3:1);}});try{assert.equal(d.querySelectorAll('.card').length,6);assert.match(d.querySelector('#message').textContent,/Cellshop/);assert.match(d.querySelector('#search-progress').textContent,/parciais/);const before=calls.filter(u=>u.searchParams.get('page')==='1').length;fail=false;d.querySelector('#retry-missing').click();await wait(()=>d.querySelector('#search-progress').textContent.includes('foram consultadas'));assert.equal(d.querySelectorAll('.card').length,8);assert.equal(calls.filter(u=>u.searchParams.get('page')==='1').length,before);}finally{dom.window.close();}});
test('late response from an old search cannot replace the new query',async()=>{let finishOld;const {dom,d,submit}=await setup({defer:true,search:u=>{const source=u.searchParams.get('source');if(u.searchParams.get('q')==='Xiaomi'&&source==='lg')return new Promise(resolve=>finishOld=resolve);return pageResponse(source,1,1,[{...stores[source],title:u.searchParams.get('q')+' '+source}]);}});try{await wait(()=>finishOld);submit('Motorola');await wait(()=>settled(d));finishOld(pageResponse('lg',1,1,[{...lg,title:'OLD RESULT'}]));await new Promise(r=>setTimeout(r,15));assert.doesNotMatch(d.querySelector('#results').textContent,/OLD RESULT/);assert.match(d.querySelector('#result-subtitle').textContent,/Motorola/);assert.equal(d.querySelectorAll('.card').length,6);}finally{dom.window.close();}});
test('confirmed and out-of-stock filters do not infer retailer stock from CP',async()=>{const {dom,d}=await setup();try{const filter=d.querySelector('#stock');filter.value='in_stock';filter.dispatchEvent(new dom.window.Event('change'));assert.equal(d.querySelectorAll('.card').length,1);assert.equal(d.querySelector('.card').dataset.key,'lg:1');filter.value='out_of_stock';filter.dispatchEvent(new dom.window.Event('change'));assert.equal(d.querySelectorAll('.card').length,1);assert.equal(d.querySelector('.card').dataset.key,'casamaringa:1');}finally{dom.window.close();}});
